baseurl: https://astampoulis.github.io/
languageCode: en-us
title: Antonis Stampoulis
theme: nofancy
pluralizelisttitles: false
author:
  name: Antonis Stampoulis
  email: antonis DOT stampoulis AT gmail DOT com
  github: astampoulis
...
